/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.touch;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bg_touch=0x7f020000;
        public static final int home=0x7f020001;
        public static final int home_pressed=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int screenshot=0x7f020004;
        public static final int screenshot_pressed=0x7f020005;
        public static final int shutdown=0x7f020006;
        public static final int shutdown_pressed=0x7f020007;
        public static final int star=0x7f020008;
        public static final int star_pressed=0x7f020009;
    }
    public static final class id {
        public static final int home=0x7f070003;
        public static final int screenshot=0x7f070000;
        public static final int shutdown=0x7f070001;
        public static final int star=0x7f070002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int scr=0x7f030001;
        public static final int touch=0x7f030002;
        public static final int touch_inflate=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int hello_world=0x7f050001;
    }
    public static final class style {
        public static final int AppTheme=0x7f060000;
    }
    public static final class xml {
        public static final int admin=0x7f040000;
        public static final int home_selector=0x7f040001;
        public static final int screenshot_selector=0x7f040002;
        public static final int shutdown_selector=0x7f040003;
        public static final int star_selector=0x7f040004;
    }
}
