/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.bistromath;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int display=0x7f060000;
        public static final int head_fx=0x7f060001;
        public static final int head_people=0x7f060010;
        public static final int head_tax=0x7f060006;
        public static final int head_tip=0x7f06000a;
        public static final int keypad=0x7f060013;
        public static final int loc_amount=0x7f060003;
        public static final int loc_people=0x7f060011;
        public static final int loc_tax=0x7f060007;
        public static final int loc_tip=0x7f06000b;
        public static final int loc_total=0x7f06000d;
        public static final int m_amount=0x7f060014;
        public static final int m_calculator=0x7f060019;
        public static final int m_expense=0x7f06001a;
        public static final int m_fx=0x7f060018;
        public static final int m_help=0x7f06001b;
        public static final int m_people=0x7f060017;
        public static final int m_tax=0x7f060015;
        public static final int m_tip=0x7f060016;
        public static final int ref_amount=0x7f060004;
        public static final int ref_people=0x7f060012;
        public static final int ref_tax=0x7f060008;
        public static final int ref_tip=0x7f06000c;
        public static final int ref_total=0x7f06000e;
        public static final int row_amount=0x7f060002;
        public static final int row_people=0x7f06000f;
        public static final int row_tax=0x7f060005;
        public static final int row_tip=0x7f060009;
    }
    public static final class layout {
        public static final int help=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class menu {
        public static final int menu=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int disp_amount=0x7f040003;
        public static final int disp_local_currency=0x7f040001;
        public static final int disp_people=0x7f040007;
        public static final int disp_ref_currency=0x7f040002;
        public static final int disp_tax=0x7f040004;
        public static final int disp_tip=0x7f040005;
        public static final int disp_total=0x7f040006;
        public static final int err_expense=0x7f040010;
        public static final int help_text=0x7f040012;
        public static final int help_title=0x7f040011;
        public static final int m_amount=0x7f040008;
        public static final int m_calculator=0x7f04000d;
        public static final int m_expense=0x7f04000e;
        public static final int m_fx=0x7f04000c;
        public static final int m_help=0x7f04000f;
        public static final int m_people=0x7f04000b;
        public static final int m_tax=0x7f040009;
        public static final int m_tip=0x7f04000a;
    }
}
