/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mycompany.myapp;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int TextView01=0x7f060010;
        public static final int TextView02=0x7f06000f;
        public static final int TextView03=0x7f06000d;
        public static final int TextView04=0x7f06000e;
        public static final int TextView05=0x7f06000c;
        public static final int button1=0x7f06000a;
        public static final int button2=0x7f06000b;
        public static final int editText1=0x7f060000;
        public static final int editText2=0x7f060003;
        public static final int editText3=0x7f060005;
        public static final int editText4=0x7f060007;
        public static final int editText5=0x7f060009;
        public static final int listView1=0x7f060011;
        public static final int textView1=0x7f060001;
        public static final int textView2=0x7f060002;
        public static final int textView3=0x7f060004;
        public static final int textView4=0x7f060006;
        public static final int textView5=0x7f060008;
    }
    public static final class layout {
        public static final int activity_buat_biodata=0x7f030000;
        public static final int activity_lihat_biodata=0x7f030001;
        public static final int activity_update_biodata=0x7f030002;
        public static final int main=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int hello_world=0x7f040001;
    }
    public static final class style {
        public static final int AppTheme=0x7f050000;
    }
}
