/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.moczul.notepad;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int ContentEditText=0x7f060005;
        public static final int TitleEditText=0x7f060003;
        public static final int addNote=0x7f060008;
        public static final int addNoteToDB=0x7f060006;
        public static final int createdAt=0x7f06000a;
        public static final int editNote=0x7f06000d;
        public static final int linearLayout3=0x7f060001;
        public static final int noteContent=0x7f06000b;
        public static final int noteList=0x7f060007;
        public static final int noteTitle=0x7f060009;
        public static final int removeNote=0x7f06000e;
        public static final int scrollView1=0x7f060000;
        public static final int showNote=0x7f06000c;
        public static final int textView1=0x7f060002;
        public static final int textView2=0x7f060004;
    }
    public static final class layout {
        public static final int createlayout=0x7f030000;
        public static final int main=0x7f030001;
        public static final int onenote=0x7f030002;
    }
    public static final class menu {
        public static final int context_menu=0x7f050000;
    }
    public static final class string {
        public static final int CtxMenuHeader=0x7f040004;
        public static final int addNoteButton=0x7f040002;
        public static final int app_name=0x7f040000;
        public static final int editNote=0x7f04000b;
        public static final int mainHeader=0x7f040003;
        public static final int noteContent=0x7f040008;
        /**  createview layout 
         */
        public static final int noteTitle=0x7f040007;
        public static final int oneNote=0x7f040001;
        public static final int removeNote=0x7f04000c;
        public static final int saveNoteButton=0x7f040009;
        /**  context menu options 
         */
        public static final int showNote=0x7f04000a;
        public static final int titleHint=0x7f04000d;
        public static final int updateNoteButton=0x7f040005;
        public static final int validation=0x7f040006;
    }
}
