/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.netmeter;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int status_icon=0x7f020001;
    }
    public static final class id {
        public static final int disp=0x7f060000;
        public static final int graph=0x7f060001;
        public static final int help=0x7f060007;
        public static final int list_item=0x7f060002;
        public static final int reset=0x7f060003;
        public static final int stop=0x7f060006;
        public static final int toggle=0x7f060004;
        public static final int top=0x7f060005;
    }
    public static final class layout {
        public static final int help=0x7f030000;
        public static final int main=0x7f030001;
        public static final int tasklist=0x7f030002;
    }
    public static final class menu {
        public static final int main_menu=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int disp_battery=0x7f04000d;
        public static final int disp_cell=0x7f04000a;
        public static final int disp_collecting=0x7f040014;
        public static final int disp_cpu=0x7f04000b;
        public static final int disp_cpu_type=0x7f04000c;
        public static final int disp_in=0x7f040010;
        public static final int disp_name=0x7f04000e;
        public static final int disp_out=0x7f040011;
        public static final int disp_system=0x7f040013;
        public static final int disp_type=0x7f04000f;
        public static final int disp_user=0x7f040012;
        public static final int disp_wifi=0x7f040009;
        public static final int help_text=0x7f040015;
        public static final int help_title=0x7f040002;
        public static final int iconized=0x7f040003;
        public static final int menu_help=0x7f040008;
        public static final int menu_reset=0x7f040004;
        public static final int menu_stop=0x7f040007;
        public static final int menu_toggle=0x7f040005;
        public static final int menu_top=0x7f040006;
        public static final int top_title=0x7f040001;
    }
}
