/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.noisealert;

public final class R {
    public static final class array {
        public static final int entries_sleep=0x7f050001;
        public static final int entries_threshold=0x7f050000;
        public static final int values_sleep=0x7f050002;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int greenbar=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int redbar=0x7f020002;
    }
    public static final class id {
        public static final int activity_led=0x7f080001;
        public static final int help=0x7f080006;
        public static final int panic=0x7f080005;
        public static final int settings=0x7f080007;
        public static final int start_stop=0x7f080003;
        public static final int status=0x7f080000;
        public static final int test=0x7f080004;
        public static final int volume=0x7f080002;
    }
    public static final class layout {
        public static final int help=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class menu {
        public static final int main_menu=0x7f070000;
    }
    public static final class string {
        public static final int alert_heading=0x7f06000a;
        public static final int alert_phone=0x7f06000c;
        public static final int alert_phone_summary=0x7f06000d;
        public static final int app_name=0x7f060000;
        public static final int call_number=0x7f060003;
        public static final int display_update=0x7f060014;
        public static final int display_update_summary=0x7f060015;
        public static final int help=0x7f060008;
        public static final int help_text=0x7f06001a;
        public static final int help_title=0x7f060019;
        public static final int no_num_msg=0x7f060017;
        public static final int no_num_title=0x7f060016;
        public static final int ok=0x7f060018;
        public static final int panic=0x7f060007;
        public static final int power_heading=0x7f06000b;
        public static final int security_code=0x7f060010;
        public static final int security_code_summary=0x7f060011;
        public static final int settings=0x7f060001;
        public static final int sleep=0x7f060012;
        public static final int sleep_summary=0x7f060013;
        public static final int sound_threshold=0x7f06000e;
        public static final int sound_threshold_summary=0x7f06000f;
        public static final int start=0x7f060004;
        public static final int stop=0x7f060005;
        public static final int stopped=0x7f060009;
        public static final int test=0x7f060006;
        public static final int threshold=0x7f060002;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
