/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.view;

public final class R {
    public static final class array {
        public static final int menu_items=0x7f040000;
    }
    public static final class attr {
    }
    public static final class id {
        public static final int action_settings=0x7f070000;
        public static final int model_load_texture=0x7f070001;
        public static final int model_toggle_animation=0x7f070005;
        public static final int model_toggle_boundingbox=0x7f070007;
        public static final int model_toggle_collision=0x7f070006;
        public static final int model_toggle_lights=0x7f070003;
        public static final int model_toggle_textures=0x7f070004;
        public static final int model_toggle_wireframe=0x7f070002;
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class menu {
        public static final int main=0x7f060000;
        public static final int menu=0x7f060001;
        public static final int model=0x7f060002;
    }
    public static final class string {
        /**  About 
         */
        public static final int about_text=0x7f03000a;
        public static final int action_settings=0x7f030002;
        /**  To review 
         */
        public static final int app_logo_desc=0x7f030017;
        public static final int app_name=0x7f030000;
        public static final int app_version=0x7f030001;
        public static final int cancel=0x7f03000e;
        /**  Help 
         */
        public static final int help_text=0x7f030009;
        public static final int image=0x7f030008;
        public static final int invert_texture_coordinates=0x7f03000d;
        /**  Demo menu 
         */
        public static final int item=0x7f030007;
        public static final int load=0x7f03000f;
        public static final int load_model=0x7f030010;
        public static final int load_texture=0x7f030016;
        /**  Load settings 
         */
        public static final int model_name=0x7f03000b;
        public static final int texture=0x7f03000c;
        public static final int title_activity_demo=0x7f030004;
        /**  Activities 
         */
        public static final int title_activity_menu=0x7f030003;
        public static final int title_activity_model=0x7f030006;
        public static final int title_activity_text=0x7f030005;
        public static final int toggle_animation=0x7f030014;
        /** <string name="toggle_skeleton">Toggle skeleton</string>
         */
        public static final int toggle_boundingbox=0x7f030015;
        public static final int toggle_lights=0x7f030013;
        public static final int toggle_textures=0x7f030012;
        /**  GL Settings 
         */
        public static final int toggle_wireframe=0x7f030011;
    }
    public static final class style {
        public static final int AppTheme=0x7f050000;
    }
}
