/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.leon.assistivetouch.main;

public final class R {
    public static final class array {
        public static final int touch_dot_size_name=0x7f040000;
        public static final int touch_dot_size_value=0x7f040001;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int background=0x7f050000;
        public static final int black=0x7f050006;
        public static final int color_diviver_line_1=0x7f050007;
        public static final int qc_normal_blue=0x7f050001;
        public static final int qc_selected_blue=0x7f050002;
        public static final int setting_blue=0x7f050008;
        public static final int trans_black=0x7f050003;
        public static final int transparent=0x7f050004;
        public static final int white=0x7f050005;
    }
    public static final class dimen {
        public static final int padding_large=0x7f060002;
        public static final int padding_medium=0x7f060001;
        public static final int padding_small=0x7f060000;
        public static final int size_dialog=0x7f060004;
        public static final int size_icon_app=0x7f060003;
    }
    public static final class drawable {
        public static final int background_holo_light=0x7f020000;
        public static final int bg_pop_pressed=0x7f020001;
        public static final int center_icon=0x7f020002;
        public static final int head_bar_button=0x7f020003;
        public static final int ic_home=0x7f020004;
        public static final int ic_launcher=0x7f020005;
        public static final int ic_launcher_pressed=0x7f020006;
        public static final int ic_sysbar_back=0x7f020007;
        public static final int ic_sysbar_home=0x7f020008;
        public static final int ic_sysbar_menu=0x7f020009;
        public static final int ic_sysbar_recent=0x7f02000a;
        public static final int ic_sysbar_search=0x7f02000b;
        public static final int item_icon_bg=0x7f02000c;
        public static final int main_assistivetouch_bg=0x7f02000d;
        public static final int selector_sysbar_bg=0x7f02000e;
        public static final int setting_title_icon=0x7f02000f;
        public static final int transparent=0x7f020010;
        public static final int transparent_view=0x7f020011;
    }
    public static final class id {
        public static final int auto_update_view=0x7f0a0003;
        public static final int boot_start_view=0x7f0a0001;
        public static final int bottom_layout=0x7f0a0007;
        public static final int enable_boot_checkbox=0x7f0a0002;
        public static final int enable_update_checkbox=0x7f0a0004;
        public static final int key_grid_item_view=0x7f0a000e;
        public static final int key_grid_view=0x7f0a0014;
        public static final int key_item_icon_img=0x7f0a000f;
        public static final int key_item_title_text=0x7f0a0010;
        public static final int menu_update=0x7f0a0015;
        public static final int service_setting_btn=0x7f0a0005;
        public static final int service_start_stop_btn=0x7f0a0000;
        public static final int settings_custom_size_view=0x7f0a000a;
        public static final int settings_input_size_edit=0x7f0a000b;
        public static final int settings_preview_img=0x7f0a0008;
        public static final int settings_save_btn=0x7f0a000d;
        public static final int settings_touch_dot_size_spinner=0x7f0a0009;
        public static final int settings_touch_dot_transparent_bar=0x7f0a000c;
        public static final int text1=0x7f0a0011;
        public static final int top_view_icon=0x7f0a0012;
        public static final int top_view_keys_layout=0x7f0a0013;
        public static final int version_textview=0x7f0a0006;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int activity_settings=0x7f030001;
        public static final int key_grid_item=0x7f030002;
        public static final int spinner_drop_view=0x7f030003;
        public static final int touch_dot_view=0x7f030004;
        public static final int touch_main_view=0x7f030005;
    }
    public static final class menu {
        public static final int activity_main=0x7f090000;
    }
    public static final class string {
        public static final int app_name=0x7f070000;
        public static final int author_info=0x7f07000a;
        public static final int dialog_cancel=0x7f07001d;
        public static final int dialog_confirm=0x7f07001c;
        public static final int dialog_setting_message=0x7f07001b;
        public static final int dialog_setting_title=0x7f07001a;
        public static final int email_info=0x7f07000b;
        public static final int enable_auto_update=0x7f070007;
        public static final int enable_boot_start=0x7f070006;
        public static final int find_update_message=0x7f070009;
        public static final int find_update_title=0x7f070008;
        public static final int key_back_name=0x7f07000f;
        public static final int key_hide_name=0x7f070013;
        public static final int key_home_name=0x7f07000e;
        public static final int key_menu_name=0x7f070011;
        public static final int key_recent_name=0x7f070010;
        public static final int key_search_name=0x7f070012;
        public static final int menu_check_update=0x7f07001e;
        public static final int menu_checking_update=0x7f07001f;
        public static final int menu_no_found_update=0x7f070020;
        public static final int no_root_tip=0x7f07000d;
        public static final int save_preferences=0x7f070019;
        public static final int service_name=0x7f070001;
        public static final int service_setting=0x7f070005;
        public static final int setting_input_touch_dot_size=0x7f070018;
        public static final int setting_touch_dot_preview=0x7f070017;
        public static final int setting_touch_dot_size=0x7f070015;
        public static final int setting_touch_dot_transparency=0x7f070016;
        public static final int start_service=0x7f070003;
        public static final int stop_service=0x7f070004;
        public static final int title_activity_main=0x7f070002;
        public static final int user_defined=0x7f070014;
        public static final int version_code=0x7f07000c;
    }
    public static final class style {
        public static final int AppTheme=0x7f080000;
        public static final int bottom_bar_btn=0x7f080002;
        public static final int setting_text_view=0x7f080004;
        public static final int setting_text_view_column_title=0x7f080005;
        public static final int setting_title_divider=0x7f080003;
        public static final int sysbar_style=0x7f080001;
    }
}
